services:
  app:
    image: perftesthelperapp
    build: .
    container_name: PerfTestHelperApp
    ports:
      - "8080:8080"
    depends_on:
      - MariaDB
      - kafka
    environment:
      db.url: jdbc:mariadb://MariaDB:3306/perftesthelperdb
      db.user: PerfTestHelperUser
      db.pass: 123
      kafka.url: kafka:9092
      kafka.self-consumer: false

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"  # for offset explorer
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka-data:/var/lib/kafka/data

  MariaDB:
    image: mariadb:latest
    container_name: perftesthelper-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: perftesthelperdb
      MARIADB_USER: PerfTestHelperUser
      MARIADB_PASSWORD: 123
      TZ: Europe/Moscow
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  kafka-data:
  mariadb-data:
