spring.application.name=PerfTestHelper

#DB
spring.datasource.url=${db.url:jdbc:mariadb://localhost:3306/perftesthelperdb}
spring.datasource.username=${db.user:PerfTestHelperUser}
spring.datasource.password=${db.pass:123}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# JWT
token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
token.expiration.seconds=86400

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.repair-on-error=true

# Kafka
spring.kafka.bootstrap-servers=${kafka.url:localhost:9092}